# Site settings
title: Vinicius Rezende
email: vinrzr@gmail.com
description: > # keep this and put description below
  Game Designer e Programador
url: "https://vinrzr.github.io" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/vinrzr/"
github_username: vinrzr
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
